// Everything readable on the home page lives here. Edit freely.
export default {
  first: "Jerad",
  last: "Griffin",
  monogram: "JG",
  discipline: "UX design & Front-end",
  workflow: "Tampa, FL",
  status: "Open to new work",
  role: 'UX designer and front-end developer building <span class="u">accessible, scalable, human-first</span> interfaces for enterprise teams — design and code, in the same pair of hands. Now shipping faster with an <strong class="ai">AI-assisted workflow</strong>.',
  openerFacts: [
    { k: "Years", v: "<b>11</b> in practice" },
    { k: "Practice", v: "Design <b>+</b> code, end to end" },
    { k: "Focus", v: "Design systems, accessibility" },
    { k: "Based", v: "Tampa, FL" },
  ],
  workIntro: "Selected projects for enterprise teams: component systems, landing pages, template systems, and training experiences.",
  aboutLede: 'I work in the seam between what looks good and <span class="u">what actually ships</span>.',
  about: [
    "I'm a UX/UI Designer & Developer with 11 years of experience creating accessible, user-focused digital solutions for global brands. Skilled in blending design strategy with front-end development to deliver seamless experiences, with a strong track record of collaboration and innovation.",
    "I bring a versatile toolkit spanning HTML, CSS, JavaScript, React, AngularJS, Wordpress, Shopify and enterprise CMS platforms, along with design expertise in Figma, Sketch, Adobe XD, and Photoshop. This balance of technical depth and creative skill enables me to deliver scalable, intuitive interfaces that align with both user needs and business goals.",
  ],
  aiCallout: "I build with an AI-accelerated workflow — using modern AI development tools to design, prototype, and ship production apps and websites dramatically faster. It's not a shortcut on quality: I pair AI's speed with hands-on craft, keeping the same bar for accessibility, performance, and clean, maintainable code. The result is more shipped, in less time, without the trade-offs.",
  stack: [
    { k: "Design", v: "Figma, Sketch, Adobe XD, Photoshop" },
    { k: "Build", v: "HTML, CSS, JavaScript, React, AngularJS" },
    { k: "Platforms", v: "WordPress, Shopify, enterprise CMS, Adobe Experience Manager" },
    { k: "AI", v: "AI-assisted design, prototyping and development" },
  ],
  clients: [
    { name: "Farm Credit Services of America", sector: "Ag finance" },
    { name: "Kraft Heinz", sector: "Consumer goods" },
    { name: "Chubb", sector: "Insurance" },
    { name: "Cornerstone OnDemand", sector: "SaaS · learning" },
    { name: "GoCanvas", sector: "SaaS · field services" },
    { name: "Palo Alto Networks", sector: "Cybersecurity" },
    { name: "Coca-Cola", sector: "Consumer brand" },
    { name: "Liberty Mutual", sector: "Insurance" },
    { name: "USPS", sector: "Public sector" },
    { name: "Amneal Pharmaceuticals", sector: "Healthcare" },
    { name: "ACE Group", sector: "Insurance" },
    { name: "IKEA", sector: "Retail" },
    { name: "Unibail-Rodamco-Westfield", sector: "Real estate" },
    { name: "Staples", sector: "Retail" },
  ],
  formAction: "https://formspree.io/f/mblznrrz",
  linkedin: "https://www.linkedin.com/in/JeradGriffin",
  github: "https://github.com/JeradGriffin",
};
